spring.application.name=backend

# JSP
server.port=8383
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#mybatis config
mybatis.config-location=classpath:mybatis-config.xml

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ev_charge
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

#한글깨짐 오류해결
server.servlet.encoding.force=true