spring.application.name=backend

# JSP
server.port=8383
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#mybatis config
mybatis.mapper-locations=classpath:/mybatis/mappers/**/*.xml
mybatis.type-aliases-package=com.ev.dto

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ev_charge
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#íê¸ê¹¨ì§ ì¤ë¥í´ê²°
server.servlet.encoding.force=true



mybatis.configuration.map-underscore-to-camel-case=true

#카카오맵 api Javascript 키
kakao.javascript.key=0487817f76d57c5d932b94b9250cbc52


#카카오 모빌리티 REST API 키
kakao.rest-api.key=73936ed3f25f5c307e9f9710359e89a7


# =========================
# Kakao OAuth2 Login
# =========================

spring.security.oauth2.client.registration.kakao.client-name=Kakao
spring.security.oauth2.client.registration.kakao.client-id=15b4da4c511ee88a2023c06a9855a593
spring.security.oauth2.client.registration.kakao.client-secret=o3AlpThSOmy7uGoCaMjwcDSASI2zAAkp
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code

spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8383/login/oauth2/code/kakao

spring.security.oauth2.client.registration.kakao.scope=profile_nickname

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id
