spring.application.name=backend

# JSP
server.port=8383
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#mybatis config
mybatis.mapper-locations=classpath:/mybatis/mappers/**/*.xml
mybatis.type-aliases-package=com.ev.dto

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ev_charge
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#íê¸ê¹¨ì§ ì¤ë¥í´ê²°
server.servlet.encoding.force=true


mybatis.configuration.map-underscore-to-camel-case=true

#카카오맵 api Javascript 키
kakao.javascript.key=0487817f76d57c5d932b94b9250cbc52


#카카오 모빌리티 REST API 키
kakao.rest-api.key=73936ed3f25f5c307e9f9710359e89a7
